session_name: itu-studio-broadcast-clock
start_directory: .
windows:
  - window_name: DEV
    layout: main-horizontal
    options:
      main-pane-height: 50
    shell_command_before:
      - . .venv/bin/activate
    panes:
      - shell_command: nvim
        focus: true
      - flask --app flaskr run
      - node
      -
