#!/usr/bin/env bash

searchterm="DataTraveler"
datapos="/home/pi/itu-studio-broadcast-clock/flaskr/data/segments.csv"
mounted=0

while true; do
    res=$(lsusb | grep $searchterm)
    if [ -n "$res" ]; then
        if [ "$mounted" == "0" ]; then
            mounted=1
            sudo mount /dev/sda1 /media/usb1
            sudo rm $datapos
            sudo cp /media/usb1/*.csv $datapos
            sudo sleep 1
            sudo xdotool key F5
        fi
    else
        echo 'B'
        sudo umount /dev/sda1
        mounted=0
    fi
    sleep 5
done
